export const guitarDirPath = "./guitar";
export const chordsDirPath = `${guitarDirPath}/chords`;

export const rootNotes = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
export const chordSuffixes = [
  "Major",
  "Minor",
  "Diminished",
  "Augmented",
  "Suspended 2nd",
  "Suspended 4th",
  "Major Flat 5th",
  "Minor Sharp 5th",
  "Minor Double Flat 5th",
  "Suspended 4th Sharp 5th",
  "Suspended 2nd Flat 5th",
  "Suspended 2nd Sharp 5th",
  "7th",
  "Minor 7th",
  "Major 7th",
  "Minor Major 7th",
  "Diminished 7th",
  "Augmented 7th",
  "Augmented Major 7th",
  "7th Flat 5th",
  "Major 7th Flat 5th",
  "Minor 7th Flat 5th",
  "Minor Major 7th Flat 5th",
  "Minor Major 7th Double Flat 5th",
  "Minor 7th Sharp 5th",
  "Minor Major 7th Sharp 5th",
  "7th Flat 9th",
  "6th",
  "Minor 6th",
  "6th Flat 5th",
  "6th Add 9th",
  "Minor 6th Add 9th",
  "9th",
  "Minor 9th",
  "Major 9th",
  "Minor Major 9th",
  "9th Flat 5th",
  "Augmented 9th",
  "9th Suspended 4th",
  "7th Sharp 9th",
  "7th Sharp 9th Flat 5th",
  "Augmented Major 9th",
  "11th",
  "Minor 11th",
  "Major 11th",
  "Minor Major 11th",
  "Major Sharp 11th",
  "13th",
  "Minor 13th",
  "Major 13th",
  "Minor Major 13th",
  "7th Suspended 2nd",
  "Major 7th Suspended 2nd",
  "7th Suspended 4th",
  "Major 7th Suspended 4th",
  "7th Suspended 2nd Sharp 5th",
  "7th Suspended 4th Sharp 5th",
  "Major 7th Suspended 4th Sharp 5th",
  "Suspended 2nd Suspended 4th",
  "7th Suspended 2nd Suspended 4th",
  "Major 7th Suspended 2nd Suspended 4th",
  "5th",
  "Major Add 9th"
];
export const shortChordSuffixes = [
  "",
  "m",
  "dim",
  "aug",
  "sus2",
  "sus4",
  "majb5",
  "m#5",
  "mbb5",
  "sus4#5",
  "sus2b5",
  "sus2#5",
  "7",
  "m7",
  "maj7",
  "mmaj7",
  "dim7",
  "aug7",
  "augmaj7",
  "7b5",
  "maj7b5",
  "m7b5",
  "mmaj7b5",
  "mmaj7bb5",
  "m7#5",
  "mmaj7#5",
  "7b9",
  "6",
  "m6",
  "6b5",
  "6add9",
  "m6add9",
  "9",
  "m9",
  "maj9",
  "mmaj9",
  "9b5",
  "aug9",
  "9sus4",
  "7#9",
  "7#9b5",
  "augmaj9",
  "11",
  "m11",
  "maj11",
  "mmaj11",
  "maj#11",
  "13",
  "m13",
  "maj13",
  "mmaj13",
  "7sus2",
  "maj7sus2",
  "7sus4",
  "maj7sus4",
  "7sus2#5",
  "7sus4#5",
  "maj7sus4#5",
  "sus2sus4",
  "7sus2sus4",
  "maj7sus2sus4",
  "5",
  "add9"
];

// aug is also noted as +
// maj is also noted as M